### ISSUE TITLE
Android API 21 throws `UnsatisfiedLinkError`

### ISSUE THREAD

**Issue by 05nelsonm** [utelle/SQLite3MultipleCiphers#114]
Getting the following exception on Android API 21 when trying to establish a connection via [sqlite-jdbc-crypt](https://github.com/Willena/sqlite-jdbc-crypt).

```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "/data/app/io.toxicity.core.data.cipher.driver.test.test-2/lib/x86_64/libsqlitejdbc.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:371)
at java.lang.System.loadLibrary(System.java:989)
at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:44)
at org.sqlite.SQLiteConnection.open(SQLiteConnection.java:283)
at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:70)
at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:19)
at org.sqlite.JDBC.createConnection(JDBC.java:104)
at org.sqlite.JDBC.connect(JDBC.java:77)
at java.sql.DriverManager.getConnection(DriverManager.java:179)
```

Unsure if this has anything to do with this project or somewhere else downstream (xerial/sqlite-jdbc or Willena/sqlite-jdbc-crypt), but wanted to ping you here to start the process.

Does `__register_atfork` ring any bells? Thanks!

**Comment by 05nelsonm** [comment]
cc: @Willena

**Comment by 05nelsonm** [comment]
Actually. This issue exists with [xerial/sqlite-jdbc](https://github.com/xerial/sqlite-jdbc).

Closing!
